# Generated by Django 6.0.6 on 2026-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=10)),
                ('label', models.CharField(help_text='Display text, e.g. "s.kislyakov84@gmail.com"', max_length=100)),
                ('value', models.CharField(help_text='Actual value, e.g. email address or @username', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Contact info',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('repo', models.CharField(help_text='GitHub repo: username/repo', max_length=200)),
                ('pypi', models.CharField(blank=True, help_text='PyPI package name (optional)', max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. Fullstack Development', max_length=100)),
                ('tagline', models.TextField(blank=True)),
                ('features', models.JSONField(default=list, help_text='List of feature strings')),
                ('links', models.JSONField(default=dict, help_text='Dict of label->url, e.g. {"pypi": "https://..."}')),
                ('badges_config', models.JSONField(default=list, help_text='List of badge objects: [{"label": "pypi", "source": "pypi_version"}]')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(choices=[('xl', 'XL'), ('lg', 'Large'), ('md', 'Medium'), ('sm', 'Small')], default='sm', max_length=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', 'Project'), ('job', 'Job'), ('present', 'Present')], max_length=10)),
                ('date_label', models.CharField(help_text='e.g. "Апрель 2026", "Январь 2026", "сейчас"', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('repo', models.CharField(blank=True, help_text='GitHub repo (for projects)', max_length=200)),
                ('url', models.URLField(blank=True, help_text='External URL (for job)')),
                ('role', models.CharField(blank=True, help_text='e.g. ИТ-Специалист', max_length=100)),
                ('date_range', models.CharField(blank=True, help_text='e.g. "Январь 2026 — настоящее время"', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
