# Generated by Django 6.0.6 on 2026-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['order'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='timelineitem',
            options={'ordering': ['order'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_type',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='label',
            field=models.CharField(help_text='Отображаемый текст', max_length=100, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='value',
            field=models.CharField(help_text='email или @username', max_length=200, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='badges_config',
            field=models.JSONField(blank=True, default=list, help_text='[{"label": "pypi", "source": "pypi_version"}]', verbose_name='Бейджи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Список характеристик', verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.JSONField(blank=True, default=dict, help_text='{"pypi": "https://...", "www": "https://..."}', verbose_name='Ссылки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pypi',
            field=models.CharField(blank=True, help_text='Название пакета на PyPI (опционально)', max_length=100, verbose_name='PyPI пакет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.CharField(help_text='GitHub: username/repo', max_length=200, verbose_name='Репозиторий'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='например: Fullstack Development', max_length=100, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tagline',
            field=models.TextField(blank=True, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='size',
            field=models.CharField(choices=[('xl', 'XL'), ('lg', 'Large'), ('md', 'Medium'), ('sm', 'Small')], default='sm', max_length=2, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_label',
            field=models.CharField(help_text='например: Апрель 2026, сейчас', max_length=100, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_range',
            field=models.CharField(blank=True, help_text='например: Январь 2026 — настоящее время', max_length=100, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='item_type',
            field=models.CharField(choices=[('project', 'Проект'), ('job', 'Работа'), ('present', 'Настоящее')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='repo',
            field=models.CharField(blank=True, help_text='GitHub репозиторий (для проектов)', max_length=200, verbose_name='Репозиторий'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='role',
            field=models.CharField(blank=True, help_text='например: ИТ-Специалист', max_length=100, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='url',
            field=models.URLField(blank=True, help_text='Внешняя ссылка (для работы)', verbose_name='Ссылка'),
        ),
    ]
