# Generated by Django 6.0.6 on 2026-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contactinfo_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Название Material Symbols иконки', max_length=50, verbose_name='Иконка'),
        ),
    ]
