# Generated by Django 6.0.6 on 2026-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.URLField(blank=True, help_text='URL изображения для карточки проекта', verbose_name='Скриншот'),
        ),
    ]
