# Generated by Django 6.0.6 on 2026-07-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_devman_monitor_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['sort_order'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['sort_order'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='timelineitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='timelineitem',
            old_name='order',
            new_name='sort_order',
        ),
    ]
