# Generated by Django 6.0.4 on 2026-10-09 08:28

from django.db import migrations, models


CATEGORY_BY_NAME = {
    # Backend
    'Python': 'backend',
    'Django': 'backend',
    'FastAPI': 'backend',
    'DRF': 'backend',
    'SQLAlchemy': 'backend',
    'PostgreSQL': 'backend',
    'SQLite': 'backend',
    'Redis': 'backend',
    'REST API': 'backend',
    'asyncio': 'backend',
    'requests': 'backend',
    'httpx': 'backend',
    'Pydantic': 'backend',
    'Celery': 'backend',
    # Web
    'HTML': 'web',
    'CSS': 'web',
    'JavaScript': 'web',
    'Bootstrap': 'web',
    'Jinja2': 'web',
    # DevOps
    'Docker': 'devops',
    'Nginx': 'devops',
    'Gunicorn': 'devops',
    'Ubuntu': 'devops',
    'Git': 'devops',
    'GitHub Actions': 'devops',
    'systemd': 'devops',
    'Linux': 'devops',
    'CI/CD': 'devops',
    # Bots & Integrations
    'Telegram Bot API': 'bots',
    'Dialogflow': 'bots',
    'aiogram': 'bots',
    'vk_api': 'bots',
    'vkbottle': 'bots',
    'VK API': 'bots',
    'pymorphy3': 'bots',
    # Tools
    'python-dotenv': 'tools',
    'opencode-py': 'tools',
    'PyPI': 'tools',
    'mypy': 'tools',
    'pytest': 'tools',
}


def assign_categories(apps, schema_editor):
    Skill = apps.get_model('main', 'Skill')
    for name, category in CATEGORY_BY_NAME.items():
        Skill.objects.filter(name=name).update(category=category)
    Skill.objects.exclude(name__in=CATEGORY_BY_NAME).update(category='tools')


def reset_categories(apps, schema_editor):
    Skill = apps.get_model('main', 'Skill')
    Skill.objects.update(category='tools')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_timeline_prior_and_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('web', 'Web'), ('devops', 'DevOps'), ('bots', 'Bots & Integrations'), ('tools', 'Tools')], default='tools', max_length=10, verbose_name='Категория'),
        ),
        migrations.RunPython(assign_categories, reset_categories),
    ]
