# Generated by Django 6.0.4 on 2026-10-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_add_dossier_pytest_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
