"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-=ugm50*d7y^wi1vbtb%2a4+3r$ee6-mjqd3g11pz7(#ymb4zon'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['132.243.121.192', 'kislyakov.pro', 'www.kislyakov.pro', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['http://132.243.121.192', 'https://kislyakov.pro', 'https://www.kislyakov.pro']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

UNFOLD = {
    "SITE_TITLE": "Dossier Admin",
    "SITE_HEADER": "Dossier Admin",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: None,
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Контент",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Навыки", "icon": "code", "link": reverse_lazy("admin:main_skill_changelist")},
                    {"title": "Проекты", "icon": "dashboard", "link": reverse_lazy("admin:main_project_changelist")},
                    {"title": "События", "icon": "timeline", "link": reverse_lazy("admin:main_timelineitem_changelist")},
                    {"title": "Контакты", "icon": "contacts", "link": reverse_lazy("admin:main_contactinfo_changelist")},
                ],
            },
            {
                "title": "Пользователи",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Пользователи", "icon": "people", "link": reverse_lazy("admin:auth_user_changelist")},
                    {"title": "Группы", "icon": "manage_accounts", "link": reverse_lazy("admin:auth_group_changelist")},
                ],
            },
        ],
    },
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 80)",
            "100": "oklch(96.7% .003 80)",
            "200": "oklch(92.8% .006 80)",
            "300": "oklch(87.2% .01 75)",
            "400": "oklch(70.7% .022 75)",
            "500": "oklch(55.1% .027 70)",
            "600": "oklch(44.6% .03 70)",
            "700": "oklch(37.3% .034 65)",
            "800": "oklch(27.8% .033 65)",
            "900": "oklch(21% .034 60)",
            "950": "oklch(13% .028 55)",
        },
        "primary": {
            "50": "oklch(97% .01 80)",
            "100": "oklch(93% .02 80)",
            "200": "oklch(88% .04 78)",
            "300": "oklch(80% .07 75)",
            "400": "oklch(72% .10 73)",
            "500": "oklch(65% .13 72)",
            "600": "oklch(57% .14 70)",
            "700": "oklch(49% .13 68)",
            "800": "oklch(42% .11 65)",
            "900": "oklch(35% .09 62)",
            "950": "oklch(25% .06 58)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = '/var/www/dossier/static'
