"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-=ugm50*d7y^wi1vbtb%2a4+3r$ee6-mjqd3g11pz7(#ymb4zon'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['kislyakov.pro', 'www.kislyakov.pro', 'localhost', '127.0.0.1', '132.243.121.192']

CSRF_TRUSTED_ORIGINS = ['https://kislyakov.pro', 'https://www.kislyakov.pro', 'http://132.243.121.192']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

UNFOLD = {
    "SITE_TITLE": "Dossier Admin",
    "SITE_HEADER": "Dossier Admin",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: None,
    "THEME": "dark",  # сайт тёмный по умолчанию; тумблер темы в админке остаётся
    "BORDER_RADIUS": "10px",
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Контент",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Навыки", "icon": "code", "link": reverse_lazy("admin:main_skill_changelist")},
                    {"title": "Проекты", "icon": "dashboard", "link": reverse_lazy("admin:main_project_changelist")},
                    {"title": "События", "icon": "timeline", "link": reverse_lazy("admin:main_timelineitem_changelist")},
                    {"title": "Контакты", "icon": "contacts", "link": reverse_lazy("admin:main_contactinfo_changelist")},
                ],
            },
            {
                "title": "Пользователи",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Пользователи", "icon": "people", "link": reverse_lazy("admin:auth_user_changelist")},
                    {"title": "Группы", "icon": "manage_accounts", "link": reverse_lazy("admin:auth_group_changelist")},
                ],
            },
        ],
    },
    "COLORS": {
        # Монохромная гамма=токены сайта (style.css :root): фон страницы #0a0a0a,
        # текст #f4f4f5/#a1a1aa/#71717a, границы #e4e4e7.
        "base": {
            "50": "#fafafa",
            "100": "#f4f4f5",
            "200": "#e4e4e7",
            "300": "#d4d4d8",
            "400": "#a1a1aa",
            "500": "#71717a",
            "600": "#52525b",
            "700": "#3f3f46",
            "800": "#27272a",
            "900": "#161618",
            "950": "#0a0a0a",
        },
        # Акцент = кислотный лайм сайта #CDFF50 (500); светлее → белый, темнее → чёрный
        "primary": {
            "50": "#fbfff1",
            "100": "#f7ffe3",
            "200": "#eeffc4",
            "300": "#e5ffa4",
            "400": "#daff7e",
            "500": "#cdff50",
            "600": "#b4e046",
            "700": "#98bd3b",
            "800": "#7b9930",
            "900": "#627a26",
            "950": "#4a5c1d",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
    # Кастомный CSS поверх unfold: self-host шрифты (Inter/Fira Code) + точечные
    # правки в стиле сайта (см. static/admin/css/themed.css)
    "STYLES": ["/static/admin/css/themed.css"],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Cache (shared across gunicorn workers, persistent). Table created via
# `python manage.py createcachetable` (run in deploy after migrate).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
        'TIMEOUT': 21600,  # 6 hours
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = '/var/www/dossier/static'
